# Generated by Django 2.2.4 on 2020-03-27 13:31

from django.db import migrations, models
import translator.models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0002_theme_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=translator.models.upload_to, verbose_name='Avatar'),
        ),
    ]
