# Generated by Django 2.2.4 on 2020-03-27 13:40

from django.db import migrations, models
import translator.models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0003_theme_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='theme',
            name='photo',
            field=models.ImageField(blank=True, upload_to=translator.models.upload_to, verbose_name='Photo link'),
        ),
    ]
