# Generated by Django 2.2.4 on 2020-03-28 07:29

from django.db import migrations, models
import translator.models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0004_auto_20200327_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, upload_to=translator.models.upload_to, verbose_name='Icon link'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='level',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='theme',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='word',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='word',
            name='sound',
            field=models.ImageField(blank=True, upload_to=translator.models.upload_to, verbose_name='Sound link'),
        ),
    ]
