# Generated by Django 2.2.4 on 2020-03-30 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0005_auto_20200328_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translator.Category'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translator.Level'),
        ),
    ]
