# Generated by Django 2.2.4 on 2020-03-27 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=155)),
                ('icon', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=155)),
                ('code', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=155)),
                ('translation', models.CharField(max_length=155)),
                ('transcription', models.CharField(max_length=155)),
                ('example', models.CharField(max_length=155)),
                ('sound', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=155)),
                ('photo', models.CharField(max_length=155)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='translator.Category')),
                ('level', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='translator.Level')),
            ],
        ),
    ]
